In [1]:
import numpy as np

**Create a NumPy array from a list**

In [2]:
list = [-2, -1, 0, 1, 2, 3, 4] 
list

[-2, -1, 0, 1, 2, 3, 4]

In [3]:
arr = np.array(list)
arr

array([-2, -1,  0,  1,  2,  3,  4])

In [4]:
type(arr)

numpy.ndarray

**Create a NumPy array from a tuple**

In [5]:
tuple = (1, 2, 4)
tuple

(1, 2, 4)

In [7]:
arr = np.array(tuple)
arr

array([1, 2, 4])

In [8]:
type(arr)

numpy.ndarray

**Creating Multi-Dimensional Array**

In [9]:
matrix = [[1,2,3], [4,5,6]]
matrix

[[1, 2, 3], [4, 5, 6]]

In [10]:
np_matrix = np.array(matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np_matrix.shape

(2, 3)

**Create a NumPy array from a list**

In [12]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
np.array([list_1, list_2, list_3])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])