In [12]:
import numpy as np

#### ***arange()***
**Return evenly spaced values within a given interval.**        
**Syntax: arange([start,] stop[, step,], dtype=None)**

In [13]:
num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

#### ***linspace()***
**Return evenly spaced numbers over a specified interval.**

In [16]:
np.linspace(1, 20, 20, retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.]),
 np.float64(1.0))

In [17]:
np.linspace(1, 20, 40, retstep=True)

(array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
         3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
         5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
         8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
        10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
        13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
        15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
        18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]),
 np.float64(0.48717948717948717))

#### ***zeros***

In [ ]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

#### ***Ones***

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### ***full***

In [20]:
np.full(5, 67, dtype = int)

array([67, 67, 67, 67, 67])

In [21]:
np.full([2, 2], 65, dtype = int)

array([[65, 65],
       [65, 65]])

#### ***empty***

In [40]:
np.empty(6, dtype=int) #Random garbage value

array([25895968444448860, 23925768161198147, 32370111954616435,
       19703527547994204, 35466212143071305,                49])

In [48]:
np.empty([4, 3], dtype=int) #Random garbage value

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### ***eye***
**Create a identity matrix**

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### ***Random***
**rand()**  
**Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)**

In [50]:
np.random.rand(4)

array([0.11550916, 0.85907468, 0.71266651, 0.63768841])

In [51]:
np.random.rand(6,4)

array([[0.89382088, 0.33878493, 0.20113893, 0.0411058 ],
       [0.71637849, 0.35963644, 0.28281594, 0.79167202],
       [0.06983985, 0.69261379, 0.92126618, 0.20290933],
       [0.76185166, 0.335339  , 0.41321744, 0.26504883],
       [0.27896932, 0.37812239, 0.84381805, 0.37875047],
       [0.63504156, 0.78181345, 0.43847993, 0.26950738]])

#### ***randn()***

***Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform. [-3, 3]***

In [53]:
np.random.randn(10, 5)

array([[ 0.7493873 ,  1.20287219,  0.48405626, -0.03347025, -1.20439016],
       [-0.13512969,  0.15281547,  1.47596222,  0.28915031,  0.2277166 ],
       [-1.30090512,  0.35514585,  1.21138416,  0.33650414, -1.7543581 ],
       [ 0.60501559,  2.15604931, -0.60584454, -0.37919631, -1.14994978],
       [ 1.21813048,  0.10709386,  0.10202016,  0.53387846, -0.18304021],
       [ 1.26062833, -0.53397686,  0.65775809, -0.22882929,  0.78976681],
       [-0.00556721, -0.72297968,  0.08045052,  0.97329255, -0.26644216],
       [-0.23431236, -0.02376836, -0.44440463, -0.68402602, -0.85856691],
       [-0.31365234,  0.15477636, -1.45800332, -0.46394056, -2.50256044],
       [ 0.46314099, -0.87237352, -0.17634472, -0.57341253,  1.56300492]])

#### ***randint()***

**Return random integers from low (inclusive) to high (exclusive).**

In [54]:
np.random.randint(1, 100, 10)

array([14, 23, 93, 71, 97,  3, 74, 56, 48, 91], dtype=int32)

In [55]:
np.random.randint(100,200,20).reshape(4,5)

array([[155, 122, 194, 192, 193],
       [151, 144, 172, 169, 134],
       [103, 104, 157, 110, 105],
       [107, 121, 140, 179, 175]], dtype=int32)

In [56]:
np.random.randint(low=1000, high=2000, size=[5,8])

array([[1065, 1789, 1052, 1622, 1542, 1823, 1580, 1854],
       [1490, 1175, 1960, 1900, 1817, 1796, 1362, 1350],
       [1969, 1520, 1421, 1179, 1581, 1545, 1784, 1013],
       [1930, 1733, 1814, 1547, 1832, 1311, 1139, 1511],
       [1039, 1548, 1953, 1809, 1554, 1583, 1360, 1534]], dtype=int32)

***max() & min()***

In [57]:
arr = np.random.randint(0,100,10)
arr

array([42, 28, 65, 61,  1, 84, 53, 84, 89, 28], dtype=int32)

In [58]:
arr.max()

np.int32(89)

In [59]:
arr.min()

np.int32(1)

#### ***argmax() & argmin()***
***To find the index locations of max and min values in array***

In [60]:
arr.argmax()

np.int64(8)

In [61]:
arr.argmin()

np.int64(4)

#### ***Inspecting Properties (Attributes)***

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)
print("Transpose:\n", arr.T)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64
Item size (bytes): 8
Total bytes: 48
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


#### ***Sorting Array***

In [64]:
a = np.array([12, 15, 10, 1])
a.sort()
a

array([ 1, 10, 12, 15])

In [65]:
a = np.array([[12, 17, 15], [10, 1, 9]])
a

array([[12, 17, 15],
       [10,  1,  9]])

In [ ]:
np.sort(a, axis = 0)    

array([[10,  1,  9],
       [12, 17, 15]])

In [67]:
np.sort(a, axis = -1)    

array([[12, 15, 17],
       [ 1,  9, 10]])

In [68]:
np.sort(a, axis = None)    

array([ 1,  9, 10, 12, 15, 17])