In [1]:
import numpy as np

#### ***Sorting Array***

In [2]:
a = np.array([12, 15, 10, 1])
a.sort()
a

array([ 1, 10, 12, 15])

In [3]:
a = np.array([[12, 17, 15], [10, 1, 9]])
a

array([[12, 17, 15],
       [10,  1,  9]])

In [4]:
np.sort(a, axis = 0)    

array([[10,  1,  9],
       [12, 17, 15]])

In [5]:
np.sort(a, axis = -1) 

array([[12, 15, 17],
       [ 1,  9, 10]])

In [6]:
np.sort(a, axis = None)  

array([ 1,  9, 10, 12, 15, 17])

**Reshape**

In [7]:
arr = np.array(np.arange(16))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
arr.reshape(8, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [9]:
arr.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

**Flatten**

In [10]:
arr2 = arr.reshape(8, 2)
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**Transpose**

In [12]:
arr2.transpose()

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

**Resize**

In [13]:
arr = np.array([1, 2, 3, 4])
arr.resize(3, 2)
arr

array([[1, 2],
       [3, 4],
       [0, 0]])

**Special Reshape**

In [14]:
arr = np.array(np.arange(16))
arr.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [15]:
arr.reshape(2, 4, -1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

**Concatenate**

In [16]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate([a, b])

array([1, 2, 3, 4])

**Split**

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]